# Dependencies: pactl, jq

[[actions]]
input_cmd = """
pactl -f json list sinks \
| jq "sort_by(.name != \\"$(pactl get-default-sink)\\")" \
| jq -r '.[] | \"\\(.index) | \\(.description)\"' \
| column -s"|" -o" " -t \
"""
preview = """
pactl -f json list sinks \
| jq --arg idx {1} '.[] | select(.index == ($idx | tonumber))' \
| jq '{name, description, driver, sample_specification, mute, volume, balance}' \
"""
show_binds = true
    [[actions.binds]]
    description = "Volume down"
    key = "ctrl-j"
    event = """\
    execute-silent(pactl set-sink-volume {1} -5%)\
    +refresh-preview\
    """
    [[actions.binds]]
    description = "Volume up"
    key = "ctrl-k"
    event = """\
    execute-silent(pactl set-sink-volume {1} +5%)\
    +refresh-preview\
    """
    [[actions.binds]]
    description = "Mute"
    key = "ctrl-m"
    event = """\
    execute-silent(pactl set-sink-mute {1} toggle)\
    +refresh-preview\
    """
    [[actions.binds]]
    description = "Set default"
    key = "ctrl-d"
    event = """\
    execute-silent(pactl set-default-sink {1})\
    +become({{}})\
    """
    [[actions.binds]]
    description = "Show full details"
    key = "ctrl-o"
    event = """\
    execute(\
        pactl -f json list sinks | \
        jq --arg idx {1} '.[] | select(.index == ($idx | tonumber))' | \
        less \
    )\
    """
    [[actions.binds]]
    description = "Switch to sources"
    key = "ctrl-s"
    event = "become({{0}} sources)"

[[actions]]
match_args = ["sources"]
input_cmd = """
pactl -f json list sources \
| jq "sort_by(.name != \\"$(pactl get-default-source)\\")" \
| jq -r '.[] | \"\\(.index) | \\(.description)\"' | \
column -s"|" -o" " -t \
"""
preview = """
pactl -f json list sources \
| jq --arg idx {1} '.[] | select(.index == ($idx | tonumber))' \
| jq '{name, description, driver, sample_specification, mute, volume, balance}' \
"""
show_binds = true
    [[actions.binds]]
    description = "Volume down"
    key = "ctrl-j"
    event = """\
    execute-silent(pactl set-source-volume {1} -5%)\
    +refresh-preview\
    """
    [[actions.binds]]
    description = "Volume up"
    key = "ctrl-k"
    event = """\
    execute-silent(pactl set-source-volume {1} +5%)\
    +refresh-preview\
    """
    [[actions.binds]]
    description = "Mute"
    key = "ctrl-m"
    event = """\
    execute-silent(pactl set-source-mute {1} toggle)\
    +refresh-preview\
    """
    [[actions.binds]]
    description = "Set default"
    key = "ctrl-d"
    event = """\
    execute-silent(pactl set-default-source {1})\
    +become({{}})\
    """
    [[actions.binds]]
    description = "Show full details"
    key = "ctrl-o"
    event = """\
    execute(\
        pactl -f json list sources | \
        jq --arg idx {1} '.[] | select(.index == ($idx | tonumber))' | \
        less\
    )\
    """
    [[actions.binds]]
    description = "Switch to sinks"
    key = "ctrl-s"
    event = "become({{0}})"
